version: "3.8"

networks:
  default:
    name: dev

services:
  postgres:
    image: postgres:16.8-alpine3.20
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  backend-core:
    build:
      context: "./backend/services/unmatched-backend-core"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis
    restart: always

  user-service:
    build:
      context: "./backend/services/user-service"
      dockerfile: "Dockerfile"
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis
    restart: always

  frontend:
    build:
      context: "./frontend/unmatched-frontend"
      dockerfile: "Dockerfile"
    env_file:
      - .env
    ports:
      - '3000:80'
    depends_on:
      - backend-core
      - user-service

volumes:
  postgres_data:
  redis_data: